from datetime import datetime

CURRENT_YEAR = datetime.now().year
CURRENT_SEASON = CURRENT_YEAR if datetime.now().month >= 9 else CURRENT_YEAR - 1

TEAM_ABBREVIATIONS = [
    "ARI",
    "ATL",
    "BAL",
    "BUF",
    "CAR",
    "CHI",
    "CIN",
    "CLE",
    "DAL",
    "DEN",
    "DET",
    "GB",
    "HOU",
    "IND",
    "JAX",
    "KC",
    "LA",
    "LAC",
    "LV",
    "MIA",
    "MIN",
    "NE",
    "NO",
    "NYG",
    "NYJ",
    "PHI",
    "PIT",
    "SEA",
    "SF",
    "TB",
    "TEN",
    "WAS",
]

TEAM_MAPPINGS = {
    # AFC East
    "bills": "BUF",
    "buffalo": "BUF",
    "buffalo bills": "BUF",
    "dolphins": "MIA",
    "miami": "MIA",
    "miami dolphins": "MIA",
    "patriots": "NE",
    "new england": "NE",
    "new england patriots": "NE",
    "pats": "NE",
    "jets": "NYJ",
    "new york jets": "NYJ",
    "ny jets": "NYJ",
    # AFC North
    "ravens": "BAL",
    "baltimore": "BAL",
    "baltimore ravens": "BAL",
    "bengals": "CIN",
    "cincinnati": "CIN",
    "cincinnati bengals": "CIN",
    "browns": "CLE",
    "cleveland": "CLE",
    "cleveland browns": "CLE",
    "steelers": "PIT",
    "pittsburgh": "PIT",
    "pittsburgh steelers": "PIT",
    # AFC South
    "texans": "HOU",
    "houston": "HOU",
    "houston texans": "HOU",
    "colts": "IND",
    "indianapolis": "IND",
    "indianapolis colts": "IND",
    "indy": "IND",
    "jaguars": "JAX",
    "jacksonville": "JAX",
    "jacksonville jaguars": "JAX",
    "jags": "JAX",
    "titans": "TEN",
    "tennessee": "TEN",
    "tennessee titans": "TEN",
    # AFC West
    "broncos": "DEN",
    "denver": "DEN",
    "denver broncos": "DEN",
    "chiefs": "KC",
    "kansas city": "KC",
    "kansas city chiefs": "KC",
    "raiders": "LV",
    "las vegas": "LV",
    "las vegas raiders": "LV",
    "chargers": "LAC",
    "los angeles chargers": "LAC",
    "la chargers": "LAC",
    # NFC East
    "cowboys": "DAL",
    "dallas": "DAL",
    "dallas cowboys": "DAL",
    "giants": "NYG",
    "new york giants": "NYG",
    "ny giants": "NYG",
    "eagles": "PHI",
    "philadelphia": "PHI",
    "philadelphia eagles": "PHI",
    "philly": "PHI",
    "commanders": "WAS",
    "washington": "WAS",
    "washington commanders": "WAS",
    # NFC North
    "bears": "CHI",
    "chicago": "CHI",
    "chicago bears": "CHI",
    "lions": "DET",
    "detroit": "DET",
    "detroit lions": "DET",
    "packers": "GB",
    "green bay": "GB",
    "green bay packers": "GB",
    "vikings": "MIN",
    "minnesota": "MIN",
    "minnesota vikings": "MIN",
    # NFC South
    "falcons": "ATL",
    "atlanta": "ATL",
    "atlanta falcons": "ATL",
    "panthers": "CAR",
    "carolina": "CAR",
    "carolina panthers": "CAR",
    "saints": "NO",
    "new orleans": "NO",
    "new orleans saints": "NO",
    "buccaneers": "TB",
    "tampa bay": "TB",
    "tampa bay buccaneers": "TB",
    "bucs": "TB",
    # NFC West
    "cardinals": "ARI",
    "arizona": "ARI",
    "arizona cardinals": "ARI",
    "cards": "ARI",
    "rams": "LA",
    "los angeles rams": "LA",
    "la rams": "LA",
    "49ers": "SF",
    "san francisco": "SF",
    "san francisco 49ers": "SF",
    "niners": "SF",
    "seahawks": "SEA",
    "seattle": "SEA",
    "seattle seahawks": "SEA",
}

TEAM_COLORS = {
    "ARI": "#97233F",
    "ATL": "#A71930",
    "BAL": "#241773",
    "BUF": "#00338D",
    "CAR": "#0085CA",
    "CHI": "#C83803",
    "CIN": "#FB4F14",
    "CLE": "#FF3C00",
    "DAL": "#003594",
    "DEN": "#FB4F14",
    "DET": "#0076B6",
    "GB": "#FFB612",
    "HOU": "#03202F",
    "IND": "#002C5F",
    "JAX": "#006778",
    "KC": "#E31837",
    "LA": "#003594",
    "LAC": "#0080C6",
    "LV": "#A5ACAF",
    "MIA": "#008E97",
    "MIN": "#4F2683",
    "NE": "#002244",
    "NO": "#D3BC8D",
    "NYG": "#0B2265",
    "NYJ": "#125740",
    "PHI": "#004C54",
    "PIT": "#FFB612",
    "SEA": "#69BE28",
    "SF": "#AA0000",
    "TB": "#D50A0A",
    "TEN": "#4B92DB",
    "WAS": "#773141",
}



# Mapping of common stat name variations to standardized names
STAT_MAPPINGS = {
    # Passing stats
    "passing yards": "passing_yards",
    "pass yards": "passing_yards",
    "yards": "passing_yards",  # Default to passing if ambiguous
    "completion percentage": "completion_rate",
    "completion rate": "completion_rate",
    "comp %": "completion_rate",
    "touchdowns": "passing_touchdowns",
    "passing tds": "passing_touchdowns",
    "ints": "interceptions",
    "picks": "interceptions",
    "yards per attempt": "yards_per_attempt",
    "ypa": "yards_per_attempt",
    # Rushing stats
    "rushing yards": "rushing_yards",
    "rush yards": "rushing_yards",
    "carries": "rushing_attempts",
    "rushing attempts": "rushing_attempts",
    "rushing touchdowns": "rushing_touchdowns",
    "rushing tds": "rushing_touchdowns",
    "yards per carry": "yards_per_carry",
    "ypc": "yards_per_carry",
    # Receiving stats
    "receiving yards": "receiving_yards",
    "rec yards": "receiving_yards",
    "receptions": "receptions",
    "catches": "receptions",
    "targets": "targets",
    "receiving touchdowns": "receiving_touchdowns",
    "receiving tds": "receiving_touchdowns",
    "yards per reception": "yards_per_reception",
    "ypr": "yards_per_reception",
    # Advanced metrics
    "expected points added": "epa",
}


# Reference: https://nflreadr.nflverse.com/articles/dictionary_player_stats.html

PLAYER_STATS_COMMON = [
    "player_id",
    "player_name",
    "player_display_name",
    "position",
    "team",
    "opponent_team",
    "season",
    "week",
    "penalties",
    "penalty_yards",
    "position_group",
    "season_type",
]

OFFENSE_POSITION_STATS = [
    "air_yards_share",
    "attempts",
    "completions",
    "fantasy_points",
    "fantasy_points_ppr",
    "receptions",
    "passing_yards",
    "passing_tds",
    "passing_int",
    "rushing_yards",
    "rushing_tds",
    "carries",
    "receiving_yards",
    "receiving_tds",
    "targets",
    "fumbles_lost",
    "sacks",
    "passing_2pt_conversions",
    "passing_air_yards",
    "passing_cpoe",
    "passing_epa",
    "passing_first_downs",
    "passing_interceptions",
    "passing_yards_after_catch",
]

PLAYER_STATS_KICKER = [
    "fg_att",
    "fg_blocked",
    "fg_blocked_distance",
    "fg_blocked_list",
    "fg_long",
    "fg_made",
    "fg_made_0_19",
    "fg_made_20_29",
    "fg_made_30_39",
    "fg_made_40_49",
    "fg_made_50_59",
    "fg_made_60_",
    "fg_made_distance",
    "fg_made_list",
    "fg_missed",
    "fg_missed_0_19",
    "fg_missed_20_29",
    "fg_missed_30_39",
    "fg_missed_40_49",
    "fg_missed_50_59",
    "fg_missed_60_",
    "fg_missed_distance",
    "fg_missed_list",
    "fg_pct",
    "gwfg_att",
    "gwfg_blocked",
    "gwfg_distance",
    "gwfg_made",
    "gwfg_missed",
    "pat_att",
    "pat_blocked",
    "pat_made",
    "pat_missed",
    "pat_pct",
]


RB_STATS = [
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_2pt_conversions",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_2pt_conversions",
    "target_share",
    "air_yards_share",
    "fantasy_points",
    "fantasy_points_ppr",
    "receiving_epa",
    "rushing_epa",
    "racr",
    "wopr",
]

WR_TE_STATS = [
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_2pt_conversions",
    "target_share",
    "air_yards_share",
    "fantasy_points",
    "fantasy_points_ppr",
    "receiving_epa",
    "rushing_epa",
    "racr",
    "wopr",
]

QB_STATS = [
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "sack_fumbles",
    "sack_fumbles_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_2pt_conversions",
    "fantasy_points",
    "fantasy_points_ppr",
    "sack_yards_lost",
    "sacks_suffered",
    "passing_cpoe",
    "passing_epa",
    "passing_interceptions",
    "wopr",
    "pacr",
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_2pt_conversions",
]

DEFENDER_STATS = [
    "def_fumbles",
    "def_fumbles_forced",
    "def_interception_yards",
    "def_interceptions",
    "def_pass_defended",
    "def_qb_hits",
    "def_sack_yards",
    "def_sacks",
    "def_safeties",
    "def_tackle_assists",
    "def_tackles_for_loss",
    "def_tackles_for_loss_yards",
    "def_tackles_solo",
    "def_tackles_with_assist",
    "def_tds",
]

OTHERS = [
    "fumble_recovery_opp",
    "fumble_recovery_own",
    "fumble_recovery_tds",
    "fumble_recovery_yards_opp",
    "fumble_recovery_yards_own",
    "headshot_url",
    "kickoff_return_yards",
    "kickoff_returns",
    "misc_yards",
    "punt_return_yards",
    "punt_returns",
    "special_teams_tds",
]


POSITION_STATS_MAP = {
    "QB": [*PLAYER_STATS_COMMON, *QB_STATS],
    "RB": [*PLAYER_STATS_COMMON, *RB_STATS],
    "WR": [*PLAYER_STATS_COMMON, *WR_TE_STATS],
    "TE": [*PLAYER_STATS_COMMON, *WR_TE_STATS],
    "K": [*PLAYER_STATS_COMMON, *PLAYER_STATS_KICKER],
    "DEF": [*PLAYER_STATS_COMMON, *DEFENDER_STATS],
    "ALL": [*PLAYER_STATS_COMMON, *OFFENSE_POSITION_STATS, *DEFENDER_STATS, *OTHERS],
}

TEAMS_STATS_SPECIALTEAMS = [
    "punt_returns",
    "punt_return_yards",
    "kickoff_returns",
    "kickoff_return_yards",
    "fg_made",
    "fg_att",
    "fg_missed",
    "fg_blocked",
    "fg_long",
    "fg_pct",
    "fg_made_0_19",
    "fg_made_20_29",
    "fg_made_30_39",
    "fg_made_40_49",
    "fg_made_50_59",
    "fg_made_60_",
    "fg_missed_0_19",
    "fg_missed_20_29",
    "fg_missed_30_39",
    "fg_missed_40_49",
    "fg_missed_50_59",
    "fg_missed_60_",
    "fg_made_list",
    "fg_missed_list",
    "fg_blocked_list",
    "fg_made_distance",
    "fg_missed_distance",
    "fg_blocked_distance",
    "pat_made",
    "pat_att",
    "pat_missed",
    "pat_blocked",
    "pat_pct",
    "gwfg_made",
    "gwfg_att",
    "gwfg_missed",
    "gwfg_blocked",
    "gwfg_distance",
    "special_teams_tds",
]
TEAM_STATS_DEFENSE = [
    "def_tackles_solo",
    "def_tackles_with_assist",
    "def_tackle_assists",
    "def_tackles_for_loss",
    "def_tackles_for_loss_yards",
    "def_fumbles_forced",
    "def_sacks",
    "def_sack_yards",
    "def_qb_hits",
    "def_interceptions",
    "def_interception_yards",
    "def_pass_defended",
    "def_tds",
    "def_fumbles",
    "def_safeties",
]
TEAM_STATS_PASSING = [
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "passing_interceptions",
    "sacks_suffered",
    "sack_yards_lost",
    "sack_fumbles",
    "sack_fumbles_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_epa",
    "passing_cpoe",
    "passing_2pt_conversions",
]
TEAMS_STATS_RUSHING = [
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_epa",
    "rushing_2pt_conversions",
]
TEAMS_STATS_RECEIVING = [
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_epa",
    "receiving_2pt_conversions",
]
TEAMS_STATS_COMMON = [
    "season",
    "week",
    "team",
    "season_type",
    "opponent_team",
]
TEAMS_STATS_OTHERS = [
    "misc_yards",
    "fumble_recovery_own",
    "fumble_recovery_yards_own",
    "fumble_recovery_opp",
    "fumble_recovery_yards_opp",
    "fumble_recovery_tds",
    "penalties",
    "penalty_yards",
    "timeouts",
]
TEAMS_STATS = {
    "COMMON": [
        *TEAMS_STATS_COMMON,
    ],
    "PASSING": [*TEAMS_STATS_COMMON, *TEAM_STATS_PASSING],
    "RUSHING": [*TEAMS_STATS_COMMON, *TEAMS_STATS_RUSHING],
    "RECEIVING": [*TEAMS_STATS_COMMON, *TEAMS_STATS_RECEIVING],
    "OFFENSE": [
        *TEAMS_STATS_COMMON,
        *TEAM_STATS_PASSING,
        *TEAMS_STATS_RUSHING,
        *TEAMS_STATS_RECEIVING,
    ],
    "OTHERS": [*TEAMS_STATS_COMMON, *TEAMS_STATS_OTHERS],
    "SPECIALTEAMS": [*TEAMS_STATS_COMMON, *TEAMS_STATS_SPECIALTEAMS],
    "DEFENSE": [*TEAMS_STATS_COMMON, *TEAM_STATS_DEFENSE],
    "ALL": [
        *TEAMS_STATS_COMMON,
        *TEAMS_STATS_SPECIALTEAMS,
        *TEAM_STATS_DEFENSE,
        *TEAM_STATS_PASSING,
        *TEAMS_STATS_RUSHING,
        *TEAMS_STATS_RECEIVING,
        *TEAMS_STATS_OTHERS,
    ],
}

QB_NEXTGEN_STATS = [
    "season",
    "season_type",
    "week",
    "player_display_name",
    "player_position",
    "team_abbr",
    "avg_time_to_throw",
    "avg_completed_air_yards",
    "avg_intended_air_yards",
    "avg_air_yards_differential",
    "aggressiveness",
    "max_completed_air_distance",
    "avg_air_yards_to_sticks",
    "attempts",
    "pass_yards",
    "pass_touchdowns",
    "interceptions",
    "passer_rating",
    "completions",
    "completion_percentage",
    "expected_completion_percentage",
    "completion_percentage_above_expectation",
    "avg_air_distance",
    "max_air_distance",
    "player_gsis_id",
    "player_first_name",
    "player_last_name",
    "player_jersey_number",
    "player_short_name",
]
