from datetime import datetime

CURRENT_YEAR = datetime.now().year
CURRENT_SEASON = CURRENT_YEAR if datetime.now().month >= 9 else CURRENT_YEAR - 1


# Mapping of common stat name variations to standardized names
STAT_MAPPINGS = {
    # Passing stats
    "passing yards": "passing_yards",
    "pass yards": "passing_yards",
    "yards": "passing_yards",  # Default to passing if ambiguous
    "completions": "completions",
    "attempts": "attempts",
    "completion percentage": "completion_rate",
    "completion rate": "completion_rate",
    "comp %": "completion_rate",
    "touchdowns": "passing_touchdowns",
    "tds": "passing_touchdowns",
    "passing tds": "passing_touchdowns",
    "interceptions": "interceptions",
    "ints": "interceptions",
    "picks": "interceptions",
    "sacks": "sacks",
    "yards per attempt": "yards_per_attempt",
    "ypa": "yards_per_attempt",
    # Rushing stats
    "rushing yards": "rushing_yards",
    "rush yards": "rushing_yards",
    "carries": "rushing_attempts",
    "rushing attempts": "rushing_attempts",
    "rushing touchdowns": "rushing_touchdowns",
    "rushing tds": "rushing_touchdowns",
    "yards per carry": "yards_per_carry",
    "ypc": "yards_per_carry",
    # Receiving stats
    "receiving yards": "receiving_yards",
    "rec yards": "receiving_yards",
    "receptions": "receptions",
    "catches": "receptions",
    "targets": "targets",
    "receiving touchdowns": "receiving_touchdowns",
    "receiving tds": "receiving_touchdowns",
    "yards per reception": "yards_per_reception",
    "ypr": "yards_per_reception",
    # Advanced metrics
    "epa": "epa",
    "expected points added": "epa",
}


# Reference: https://nflreadr.nflverse.com/articles/dictionary_player_stats.html

COMMON_STATS = [
    "player_id",
    "player_name",
    "player_display_name",
    "position",
    "team",
    "opponent_team",
    "season",
    "week",
    "penalties",
    "penalty_yards",
    "position_group",
    "season_type",
]

OFFENSE_POSITION_STATS = [
    *COMMON_STATS,
    "air_yards_share",
    "attempts",
    "completions",
    "fantasy_points",
    "fantasy_points_ppr",
    "receptions",
    "passing_yards",
    "passing_tds",
    "passing_int",
    "rushing_yards",
    "rushing_tds",
    "carries",
    "receiving_yards",
    "receiving_tds",
    "targets",
    "fumbles_lost",
    "sacks",
    "passing_2pt_conversions",
    "passing_air_yards",
    "passing_cpoe",
    "passing_epa",
    "passing_first_downs",
    "passing_interceptions",
    "passing_yards_after_catch",
]

KICKER_STATS = [
    "fg_att",
    "fg_blocked",
    "fg_blocked_distance",
    "fg_blocked_list",
    "fg_long",
    "fg_made",
    "fg_made_0_19",
    "fg_made_20_29",
    "fg_made_30_39",
    "fg_made_40_49",
    "fg_made_50_59",
    "fg_made_60_",
    "fg_made_distance",
    "fg_made_list",
    "fg_missed",
    "fg_missed_0_19",
    "fg_missed_20_29",
    "fg_missed_30_39",
    "fg_missed_40_49",
    "fg_missed_50_59",
    "fg_missed_60_",
    "fg_missed_distance",
    "fg_missed_list",
    "fg_pct",
    "gwfg_att",
    "gwfg_blocked",
    "gwfg_distance",
    "gwfg_made",
    "gwfg_missed",
    "pat_att",
    "pat_blocked",
    "pat_made",
    "pat_missed",
    "pat_pct",
]


RB_STATS = [
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_2pt_conversions",
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_2pt_conversions",
    "target_share",
    "air_yards_share",
    "fantasy_points",
    "fantasy_points_ppr",
    "receiving_epa",
    "rushing_epa",
    "racr",
    "wopr",
]

WR_TE_STATS = [
    "receptions",
    "targets",
    "receiving_yards",
    "receiving_tds",
    "receiving_fumbles",
    "receiving_fumbles_lost",
    "receiving_air_yards",
    "receiving_yards_after_catch",
    "receiving_first_downs",
    "receiving_2pt_conversions",
    "target_share",
    "air_yards_share",
    "fantasy_points",
    "fantasy_points_ppr",
    "receiving_epa",
    "rushing_epa",
    "racr",
    "wopr",
]

QB_STATS = [
    "completions",
    "attempts",
    "passing_yards",
    "passing_tds",
    "sack_fumbles",
    "sack_fumbles_lost",
    "passing_air_yards",
    "passing_yards_after_catch",
    "passing_first_downs",
    "passing_2pt_conversions",
    "fantasy_points",
    "fantasy_points_ppr",
    "sack_yards_lost",
    "sack_yards_lost",
    "sacks_suffered",
    "passing_cpoe",
    "passing_epa",
    "passing_interceptions",
    "wopr",
    "pacr",
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_fumbles",
    "rushing_fumbles_lost",
    "rushing_first_downs",
    "rushing_2pt_conversions",
]

DEFENDER_STATS = [
    "def_fumbles",
    "def_fumbles_forced",
    "def_interception_yards",
    "def_interceptions",
    "def_pass_defended",
    "def_qb_hits",
    "def_sack_yards",
    "def_sacks",
    "def_safeties",
    "def_tackle_assists",
    "def_tackles_for_loss",
    "def_tackles_for_loss_yards",
    "def_tackles_solo",
    "def_tackles_with_assist",
    "def_tds",
]

OTHERS = [
    "fumble_recovery_opp",
    "fumble_recovery_own",
    "fumble_recovery_tds",
    "fumble_recovery_yards_opp",
    "fumble_recovery_yards_own",
    "headshot_url",
    "kickoff_return_yards",
    "kickoff_returns",
    "misc_yards",
    "punt_return_yards",
    "punt_returns",
    "special_teams_tds",
]


POSITION_STATS_MAP = {
    "QB": [*COMMON_STATS, *QB_STATS],
    "RB": [*COMMON_STATS, *RB_STATS],
    "WR": [*COMMON_STATS, *WR_TE_STATS],
    "TE": [*COMMON_STATS, *WR_TE_STATS],
    "K": [*COMMON_STATS, *KICKER_STATS],
}

TEAM_MAPPINGS = {
    "chiefs": "Kansas City Chiefs",
    "kc": "Kansas City Chiefs",
    "kansas city": "Kansas City Chiefs",
    "bills": "Buffalo Bills",
    "buffalo": "Buffalo Bills",
    "bengals": "Cincinnati Bengals",
    "cincinnati": "Cincinnati Bengals",
    "49ers": "San Francisco 49ers",
    "niners": "San Francisco 49ers",
    "san francisco": "San Francisco 49ers",
    "cowboys": "Dallas Cowboys",
    "dallas": "Dallas Cowboys",
    "eagles": "Philadelphia Eagles",
    "philadelphia": "Philadelphia Eagles",
    "philly": "Philadelphia Eagles",
}
