---
config:
  flowchart:
    curve: stepAfter
fontFamily: Arial
look: handDrawn
theme: neutral
---
graph TD;
	__start__([<p>__start__</p>]):::first
	entry(entry)
	exit(exit)
	query_parser(query_parser)
	retriever(retriever)
	AnalyzerReactAgent(AnalyzerReactAgent)
	generate_visualization(generate_visualization<hr/><small><em>__interrupt = before</em></small>):::hitl
	execute_visualization(execute_visualization<hr/><small><em>__interrupt = before</em></small>):::hitl
	save_report(save_report<hr/><small><em>__interrupt = before</em></small>):::hitl
	approval(approval<hr/><small><em>__interrupt = before</em></small>):::hitl
	__end__([<p>__end__</p>]):::last
	AnalyzerReactAgent -.-> approval;
	AnalyzerReactAgent -.-> exit;
	AnalyzerReactAgent -.-> generate_visualization;
	AnalyzerReactAgent -.-> save_report;
	__start__ --> entry;
	approval --> retriever;
	entry -.-> exit;
	entry -.-> query_parser;
	execute_visualization --> save_report;
	generate_visualization --> execute_visualization;
	query_parser -.-> exit;
	query_parser -.-> retriever;
	retriever -.-> AnalyzerReactAgent;
	retriever -.-> exit;
	save_report --> exit;
	exit --> __end__;
	classDef default fill:#E1F5FE,stroke:#01579B,stroke-width:2px,color:#000000,line-height:1.2
	classDef first fill:#D1C4E9,stroke-dasharray: 5 5,color:#000000
	classDef last fill:#D1C4E9,stroke:#4A148C,stroke-width:2px,color:#000000

	classDef hitl fill:#FFF3E0,stroke:#E65100,stroke-width:2px,color:#000000

    subgraph Legend
        direction LR
        L1(System Step):::default
        L2(Start / End):::first
        L3(Human Action):::hitl
    end
